# Generated by Django 4.2.30 on 2026-06-22 08:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAlbumPage',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер страницы')),
                ('width', models.FloatField(default=210, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(300)], verbose_name='Ширина (мм)')),
                ('height', models.FloatField(default=297, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(300)], verbose_name='Высота (мм)')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата обновления')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Страница альбома',
                'verbose_name_plural': 'historical Страницы альбомов',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPhoto',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название фото')),
                ('file', models.TextField(max_length=100, verbose_name='Файл изображения')),
                ('width', models.IntegerField(default=0, verbose_name='Ширина (px)')),
                ('height', models.IntegerField(default=0, verbose_name='Высота (px)')),
                ('size', models.BigIntegerField(default=0, verbose_name='Размер (байты)')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='Дата загрузки')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата обновления')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Фотография',
                'verbose_name_plural': 'historical Фотографии',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPhotoPlacement',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('x', models.FloatField(default=0, verbose_name='Позиция X (мм)')),
                ('y', models.FloatField(default=0, verbose_name='Позиция Y (мм)')),
                ('width', models.FloatField(validators=[django.core.validators.MinValueValidator(10)], verbose_name='Ширина (мм)')),
                ('height', models.FloatField(validators=[django.core.validators.MinValueValidator(10)], verbose_name='Высота (мм)')),
                ('rotation', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)], verbose_name='Поворот (градусы)')),
                ('z_index', models.IntegerField(default=0, verbose_name='Порядок слоев')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата обновления')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Размещение фото',
                'verbose_name_plural': 'historical Размещения фото',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveField(
            model_name='albumformat',
            name='created_by_user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_by_user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='format',
        ),
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userimage',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='covertype',
            options={'ordering': ['name'], 'verbose_name': 'Тип обложки', 'verbose_name_plural': 'Типы обложек'},
        ),
        migrations.AlterModelOptions(
            name='historicalphotoalbum',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Фотоальбом', 'verbose_name_plural': 'historical Фотоальбомы'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-created_at'], 'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AlterModelOptions(
            name='photoalbum',
            options={'ordering': ['-created_at'], 'verbose_name': 'Фотоальбом', 'verbose_name_plural': 'Фотоальбомы'},
        ),
        migrations.AlterModelOptions(
            name='photoplacement',
            options={'ordering': ['page', 'z_index'], 'verbose_name': 'Размещение фото', 'verbose_name_plural': 'Размещения фото'},
        ),
        migrations.RemoveField(
            model_name='covertype',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='photoplacement',
            name='scale',
        ),
        migrations.RemoveField(
            model_name='photoplacement',
            name='x_position',
        ),
        migrations.RemoveField(
            model_name='photoplacement',
            name='y_position',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_formats',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.AddField(
            model_name='albumpage',
            name='height',
            field=models.FloatField(default=297, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(300)], verbose_name='Высота (мм)'),
        ),
        migrations.AddField(
            model_name='albumpage',
            name='width',
            field=models.FloatField(default=210, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(300)], verbose_name='Ширина (мм)'),
        ),
        migrations.AddField(
            model_name='covertype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='covertype',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='height',
            field=models.IntegerField(default=0, verbose_name='Высота (px)'),
        ),
        migrations.AddField(
            model_name='photo',
            name='size',
            field=models.BigIntegerField(default=0, verbose_name='Размер (байты)'),
        ),
        migrations.AddField(
            model_name='photo',
            name='width',
            field=models.IntegerField(default=0, verbose_name='Ширина (px)'),
        ),
        migrations.AddField(
            model_name='photoplacement',
            name='height',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(10)], verbose_name='Высота (мм)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photoplacement',
            name='rotation',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)], verbose_name='Поворот (градусы)'),
        ),
        migrations.AddField(
            model_name='photoplacement',
            name='width',
            field=models.FloatField(default=500, validators=[django.core.validators.MinValueValidator(10)], verbose_name='Ширина (мм)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photoplacement',
            name='x',
            field=models.FloatField(default=0, verbose_name='Позиция X (мм)'),
        ),
        migrations.AddField(
            model_name='photoplacement',
            name='y',
            field=models.FloatField(default=0, verbose_name='Позиция Y (мм)'),
        ),
        migrations.AddField(
            model_name='photoplacement',
            name='z_index',
            field=models.IntegerField(default=0, verbose_name='Порядок слоев'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Биография'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания профиля'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='albumpage',
            name='page_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер страницы'),
        ),
        migrations.AlterField(
            model_name='covertype',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название типа обложки'),
        ),
        migrations.AlterField(
            model_name='historicalphotoalbum',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='historicalphotoalbum',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('in_progress', 'В процессе редактирования'), ('completed', 'Завершен'), ('printing', 'На печати'), ('delivered', 'Доставлен')], db_index=True, default='draft', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='historicalphotoalbum',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Название альбома'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата загрузки'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to='user_photos/%Y/%m/%d/', verbose_name='Файл изображения'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='photoalbum',
            name='cover_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='albums.covertype', verbose_name='Тип обложки'),
        ),
        migrations.AlterField(
            model_name='photoalbum',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='photoalbum',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('in_progress', 'В процессе редактирования'), ('completed', 'Завершен'), ('printing', 'На печати'), ('delivered', 'Доставлен')], db_index=True, default='draft', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='photoalbum',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Название альбома'),
        ),
        migrations.AlterField(
            model_name='photoplacement',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='albums.photo', verbose_name='Фотография'),
        ),
        migrations.AddIndex(
            model_name='albumpage',
            index=models.Index(fields=['album', 'page_number'], name='album_pages_album_i_493d4e_idx'),
        ),
        migrations.AddIndex(
            model_name='covertype',
            index=models.Index(fields=['name'], name='cover_types_name_7a91f3_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['user', '-created_at'], name='photos_user_id_e02474_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['user', 'created_at'], name='photos_user_id_50648a_idx'),
        ),
        migrations.AddIndex(
            model_name='photoalbum',
            index=models.Index(fields=['user', 'status'], name='photo_album_user_id_4904fb_idx'),
        ),
        migrations.AddIndex(
            model_name='photoalbum',
            index=models.Index(fields=['user', '-created_at'], name='photo_album_user_id_998445_idx'),
        ),
        migrations.AddIndex(
            model_name='photoalbum',
            index=models.Index(fields=['status'], name='photo_album_status_7b419a_idx'),
        ),
        migrations.AddIndex(
            model_name='photoalbum',
            index=models.Index(fields=['created_at'], name='photo_album_created_f44b6f_idx'),
        ),
        migrations.AddIndex(
            model_name='photoplacement',
            index=models.Index(fields=['page'], name='photo_place_page_id_ea5da6_idx'),
        ),
        migrations.AddIndex(
            model_name='photoplacement',
            index=models.Index(fields=['photo'], name='photo_place_photo_i_481ca1_idx'),
        ),
        migrations.AlterModelTable(
            name='albumpage',
            table='album_pages',
        ),
        migrations.AlterModelTable(
            name='covertype',
            table='cover_types',
        ),
        migrations.AlterModelTable(
            name='photo',
            table='photos',
        ),
        migrations.AlterModelTable(
            name='photoalbum',
            table='photo_albums',
        ),
        migrations.AlterModelTable(
            name='photoplacement',
            table='photo_placements',
        ),
        migrations.DeleteModel(
            name='AlbumFormat',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='UserImage',
        ),
        migrations.AddField(
            model_name='historicalphotoplacement',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalphotoplacement',
            name='page',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='albums.albumpage', verbose_name='Страница'),
        ),
        migrations.AddField(
            model_name='historicalphotoplacement',
            name='photo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='albums.photo', verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='historicalphoto',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalphoto',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='historicalalbumpage',
            name='album',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='albums.photoalbum', verbose_name='Альбом'),
        ),
        migrations.AddField(
            model_name='historicalalbumpage',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
