# Generated by Django 4.2.30 on 2026-06-17 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField(verbose_name='Номер страницы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Страница альбома',
                'verbose_name_plural': 'Страницы альбомов',
                'ordering': ['album', 'page_number'],
            },
        ),
        migrations.CreateModel(
            name='CoverType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название типа обложки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Тип обложки',
                'verbose_name_plural': 'Типы обложек',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название фото')),
                ('file', models.ImageField(upload_to='user_photos/', verbose_name='Файл изображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия'),
        ),
        migrations.CreateModel(
            name='PhotoPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_position', models.FloatField(default=0.0, verbose_name='Позиция X')),
                ('y_position', models.FloatField(default=0.0, verbose_name='Позиция Y')),
                ('scale', models.FloatField(default=1.0, verbose_name='Масштаб')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='albums.albumpage', verbose_name='Страница')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.photo', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Размещение фото',
                'verbose_name_plural': 'Размещения фото',
            },
        ),
        migrations.CreateModel(
            name='PhotoAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название альбома')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('Draft', 'Черновик'), ('Printing', 'В печати'), ('Completed', 'Завершен')], default='Draft', max_length=50, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('cover_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='albums.covertype', verbose_name='Тип обложки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_albums', to='albums.user', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Фотоальбом (новый)',
                'verbose_name_plural': 'Фотоальбомы (новые)',
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.user', verbose_name='Владелец'),
        ),
        migrations.CreateModel(
            name='HistoricalPhotoAlbum',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название альбома')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('Draft', 'Черновик'), ('Printing', 'В печати'), ('Completed', 'Завершен')], default='Draft', max_length=50, verbose_name='Статус')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата обновления')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cover_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='albums.covertype', verbose_name='Тип обложки')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='albums.user', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'historical Фотоальбом (новый)',
                'verbose_name_plural': 'historical Фотоальбомы (новые)',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='albumpage',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='albums.photoalbum', verbose_name='Альбом'),
        ),
        migrations.AlterUniqueTogether(
            name='albumpage',
            unique_together={('album', 'page_number')},
        ),
    ]
